### ISSUE TITLE
Remove clipboard alias

### ISSUE THREAD

**Issue by Slackadays** [emilknievel/dotfiles#1]
I found your dotfiles after searching GH for all mentions of `xclip`. In commit https://github.com/emilknievel/dotfiles/commit/e34c56b3ba97c8cc02bbbb36833f577dd374e11a, you added a `clipboard` alias for a specific invocation of `xclip` which is a bit of a hack. I just wanted to suggest you my project Clipboard which would be able to have the same `clipboard` command name as well as a shorter `cb`, and it would make your dotfiles portable to Wayland/macOS too. As a side effect, you'd also be able to copy regular files and directories directly because CB supports those natively.

Hope this helps! :)

**Comment by emilknievel** [comment]
Hey, that's very nice of you. I'll make sure to check it out and give it a star as well :)

**Comment by emilknievel** [comment]
Regarding my dotfiles, I haven't really kept up with documenting all the prerequisites (it's a work in progress). Just in case it's something you're interested in making use of. That Clipboard project looks really promising btw :)
